# Generated by Django 4.1.1 on 2022-10-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_newdatatotable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created",),
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
